config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  mount GrapeSwaggerRails::Engine => '/swagger'
  mount API => '/'

  devise_for :users

  resources :rooms, only: [:new, :create, :show, :index]
  resources :messages
  
  root to: "rooms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
# == Schema Information
#
# Table name: attachments
#
#  id          :integer          not null, primary key
#  title       :string
#  title_url   :string
#  description :text
#  image_url   :string
#  message_id  :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Attachment < ApplicationRecord
  belongs_to :message
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id          :integer          not null, primary key
#  body        :text
#  sender_name :string
#  sent_at     :datetime
#  user_id     :integer
#  room_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  has_many :attachments

  validates :body, presence: true, length: {minimum: 1, maximum: 1000}

  after_create_commit { BroadcastJob.perform_later(self) }
  before_save { self.sender_name = self.user.name }

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end

end

app/models/room.rb
# == Schema Information
#
# Table name: rooms
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :users, through: :messages
  validates :name, presence: true, uniqueness: true, case_sensitive: false
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  name                   :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  authentication_token   :string
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages
  has_many :rooms, through: :messages
  validates :name, presence: true, uniqueness: true

  before_validation(on: :create) do
  	self.name = self.email.split('@').first
  end

  before_save :ensure_authentication_token

  def ensure_authentication_token
    if authentication_token.blank?
      self.authentication_token = generate_authentication_token
    end
  end

  private
  
  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless User.where(authentication_token: token).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @rooms = Room.all
  end

  def show
    @room = Room.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    digest_email = Digest::MD5.hexdigest(user.email)
    gravatar_url = "https://www.gravatar.com/avatar/#{digest_email}?s=#{opts.delete(:size) { 40 }}"
    image_tag gravatar_url, opts
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Messenger</title>
    <link href="https://bootswatch.com/cerulean/bootstrap.min.css" rel="stylesheet" media="screen">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="container">
      <div class="jumbotron">
        <h1>Micro Messenger</h1>
        <p>Tiny service that broadcasts messages. You can find the full api doc on<a href="/swagger" class="btn">Swagger</a>.</p>
      </div>
      <div class="row">
        <%= yield %>
      </div>
    </div>
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/rooms/_attachment.html.erb
<% if attachment.image_url %>
  <a href="<%= attachment.image_url %>"><img src="<%= attachment.image_url %>" width=150 height=150 /></a>
<% else %>
  <p>
    <a href="<%= attachment.title_url %>"><%= attachment.title || '...' %></a>
    <br>
    <span>
      <%= attachment.description %>
    </span>
  </p>
<% end %>

app/views/rooms/_message.html.erb
<div class="card">
  <div class="card-block">
    <div class="row">
      <div class="col-md-1">
        <%= gravatar_for message.user %>
      </div>
      <div class="col-md-10">
        <p class="card-text">
          <span class="text-muted"><%= message.user.name %> at <%= message.timestamp %> says</span><br>
          <%= message.body %>
        </p>
        <% if message.attachments.any? %>
          <p class="card-text">
            <span class="text-muted">attachments</span><br>
            <%= render partial: 'rooms/attachment', collection: message.attachments %>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= link_to 'Show', room %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div>
  Your API Token: <%= current_user.authentication_token %>
</div>

<br>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<div class="row">
<div id="messages" data-chat-room-id="<%= @room.id %>" class="col-md-12">
  <%= render partial: 'rooms/message', collection: @room.messages %>
</div>
</div>

<%= form_for @message, url: '#' do |f| %>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
    <small class="text-muted">From 2 to 1000 characters</small>
  </div>

  <%= f.submit "Post", class: 'btn btn-primary btn-lg' %>
<% end %>

<%= link_to 'Back', rooms_path %>